apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanoshimu-web-deployment
  labels:
    app: tanoshimu-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanoshimu-web
  template:
    metadata:
      labels:
        app: tanoshimu-web
    spec:
      containers:
        - name: tanoshimu-web
          image: docker.io/drummeraki/tanoshimu-web:live
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_HOST
              value: http://tanoshimu.akinyele-demos.ca:31001

---
apiVersion: v1
kind: Service
metadata:
  name: tanoshimu-web-service
spec:
  type: NodePort
  selector:
    app: tanoshimu-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
